/* Generated by :claw at 2020-12-06T16:39:15.048151Z */

#if defined(__cplusplus)
#include <new>
#endif



#include "SOIL2/SOIL2.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif



#if defined(__cplusplus)
}
#endif
